badges = [
    {
        "Badge": "24LU107121",
        "Install Date": "02/01/2024",
        "Service Point": 1770604428,
        "DMA": 82.1,
        "Postcode": "NR31",
        "Region": "Suffolk",
        "Alert present": "Y",
        "Alert Type": "Leakage",
        "Under Investigation": True,
        "SR Code": "LKTC"
    },
    {
        "Badge": "24LU107285",
        "Install Date": "29/02/2024",
        "Service Point": 2870648767,
        "DMA": 83.8,
        "Postcode": "NR32",
        "Region": "Suffolk",
        "Alert present": "N",
        "Alert Type": "",
        "Under Investigation": False,
        "SR Code": ""
    },
    {
        "Badge": "24LU107379",
        "Install Date": "11/04/2024",
        "Service Point": 3920796104,
        "DMA": 84.9,
        "Postcode": "NR34",
        "Region": "Suffolk",
        "Alert present": "N",
        "Alert Type": "",
        "Under Investigation": False,
        "SR Code": ""
    },
    {
        "Badge": "24LU107407",
        "Install Date": "14/05/2024",
        "Service Point": 4510705917,
        "DMA": 87.2,
        "Postcode": "NR35",
        "Region": "Suffolk",
        "Alert present": "Y",
        "Alert Type": "No consumption",
        "Under Investigation": False,
        "SR Code": ""
    },
    {
        "Badge": "24LU107588",
        "Install Date": "20/06/2024",
        "Service Point": 5320259997,
        "DMA": 89.1,
        "Postcode": "IP18",
        "Region": "Suffolk",
        "Alert present": "N",
        "Alert Type": "",
        "Under Investigation": False,
        "SR Code": ""
    },
    {
        "Badge": "24PA99417656",
        "Install Date": "13/02/2024",
        "Service Point": 6770604428,
        "DMA": 38.02,
        "Postcode": "CM8",
        "Region": "Essex",
        "Alert present": "N",
        "Alert Type": "",
        "Under Investigation": False,
        "SR Code": ""
    },
    {
        "Badge": "24PA99417754",
        "Install Date": "21/03/2024",
        "Service Point": 7870648767,
        "DMA": 46.07,
        "Postcode": "CM11",
        "Region": "Essex",
        "Alert present": "Y",
        "Alert Type": "High consumption",
        "Under Investigation": False,
        "SR Code": ""
    },
    {
        "Badge": "24PA99417858",
        "Install Date": "30/05/2024",
        "Service Point": 8920796104,
        "DMA": 57.02,
        "Postcode": "CM0",
        "Region": "Essex",
        "Alert present": "N",
        "Alert Type": "",
        "Under Investigation": False,
        "SR Code": ""
    },
    {
        "Badge": "24PA99417947",
        "Install Date": "07/06/2024",
        "Service Point": 9510705917,
        "DMA": 61.02,
        "Postcode": "CM2",
        "Region": "Essex",
        "Alert present": "N",
        "Alert Type": "",
        "Under Investigation": False,
        "SR Code": ""
    },
    {
        "Badge": "24PA99417050",
        "Install Date": "15/07/2024",
        "Service Point": 320259997,
        "DMA": 77.01,
        "Postcode": "CM3",
        "Region": "Essex",
        "Alert present": "N",
        "Alert Type": "",
        "Under Investigation": False,
        "SR Code": ""
    },
    {
        "Badge": "24LU987654",
        "Install Date": "05/05/2024",
        "Service Point": "0987654321",
        "DMA": 50.0,
        "Postcode": "CM7",
        "Region": "Essex",
        "Alert present": "N",
        "Alert Type": "",
        "Under Investigation": False,
        "SR Code": ""
    }
]